CREATE DATABASE BD_ACG
GO

USE BD_ACG
GO

CREATE TABLE ACG(
	ID			INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	NOME		VARCHAR(100),
	HORAS		INT,
	MODALIDADE	VARCHAR(50),
	TIPO		VARCHAR(50)
)

CREATE TABLE ALUNO(
	ID			INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	NOME		VARCHAR(50),
	EMAIL		VARCHAR(50),
	MATRICULA	CHAR(7),
	SENHA		VARCHAR(30),
	APROVADO	VARCHAR(10)
)

CREATE TABLE ENVIO(
	FK_ACG			INT,
	FK_ALUNO		INT,
	FOREIGN KEY (FK_ACG) REFERENCES ACG(ID),
	FOREIGN KEY (FK_ALUNO) REFERENCES ALUNO(ID)
)


INSERT INTO ACG (nome, modalidade, tipo, horas) VALUES ('ASSEDIO', 'Formação Profissional','PALESTRA', 3)
INSERT INTO ACG (nome, modalidade, tipo, horas) VALUES ('INTERNET', 'Extensão Universitária', 'CURSO', 4)
INSERT INTO ACG (nome, modalidade, tipo, horas) VALUES ('LINGUAGEM', 'Pesquisa', 'PALESTRA', 2)
INSERT INTO ACG (nome, modalidade, tipo, horas) VALUES ('FIGMA', 'Ensino', 'CURSO', 7)

INSERT INTO ALUNO (NOME, EMAIL,MATRICULA,SENHA) VALUES ('HENRIQUE', 'HENRIQUE@', '2121212', '321')
INSERT INTO ALUNO (NOME, EMAIL,MATRICULA,SENHA) VALUES ('HENRY', 'X@', '3216547', '321')
INSERT INTO ALUNO (NOME, EMAIL,MATRICULA,SENHA) VALUES ('MATEUS', 'Y@', '7894561', '321')
INSERT INTO ALUNO (NOME, EMAIL,MATRICULA,SENHA) VALUES ('IARA', 'Z@', '6543218', '321')

INSERT INTO ENVIO VALUES (4, 2)

SELECT * FROM ACG
SELECT * FROM ALUNO
SELECT * FROM ENVIO

								--SOMA DAS HORAS TOTAIS DE UM ALUNO ESPEFÍFICO

--PROCURA NO BANCO DE DADOS O ID DO ALUNO ATRAVES DA MATRICULA
SELECT ID FROM ALUNO WHERE MATRICULA = '7894561' --RECEBE A MATRICULA DO C#

--PEGA O ID DO CURSO SELECIONADO NO COMBOBOX, JUNTAMENTE COM O ID DO ALUNO IDENTIFICADO ANTERIORMENTE E INSERE NA TABELA 'ENVIO'
INSERT INTO ENVIO VALUES (2, 1)

--FAZ A SOMA DAS HORAS DE ACG ENVIADAS PELO ALUNO X
SELECT SUM(HORAS) AS 'HORA TOTAL' FROM ENVIO JOIN ACG ON ACG.ID = ENVIO.FK_ACG WHERE ENVIO.FK_ALUNO = 3



--SELECT * FROM ENVIO WHERE FK_ALUNO = 2

--DROP TABLE ACG
--DROP TABLE ALUNO
--DROP TABLE ENVIO