CREATE DATABASE BD_ACG;
GO

USE BD_ACG;
GO

CREATE TABLE ACG(
	ID			INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	NOME		VARCHAR(100),
	HORAS		INT,
	MODALIDADE	VARCHAR(50),
	TIPO		VARCHAR(50)
);
GO

CREATE TABLE ALUNO(
	ID			INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	NOME		VARCHAR(50),
	EMAIL		VARCHAR(50),
	MATRICULA	CHAR(7),
	SENHA		VARCHAR(30)
);
GO

CREATE TABLE ENVIO(
	ID_ACG			INT,
	ID_ALUNO		INT,
	ACEITO			INT,
	FOREIGN KEY (ID_ACG) REFERENCES ACG(ID),
	FOREIGN KEY (ID_ALUNO) REFERENCES ALUNO(ID)
);
GO

SELECT * FROM ACG;
SELECT * FROM ALUNO;
SELECT * FROM ENVIO;
GO